### ISSUE TITLE
remove lines 66+67

### ISSUE THREAD

**Issue by mlaplante** [rickyaward/Rickyaward#6]

**Comment by rickyaward** [comment]
after removing lives 4-6, 66 add 67 are no longer in the same spot, so do you mean remove 
<select>
            <option>Pick your favorite food</option

**Comment by mlaplante** [comment]
@rickyaward The <footer > tags

**Comment by mlaplante** [comment]
footer

**Comment by mlaplante** [comment]
@rickyaward lines 86 - 88
